server.port=8082

eureka.client.service-url.defaultZone=http://${EUREKA_HOST:localhost}:8761/eureka

# CLIENTE-SERVICE
spring.cloud.gateway.server.webmvc.routes[0].id=servicio1
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://Cliente-Service
spring.cloud.gateway.server.webmvc.routes[0].predicates=Path=/api/clie/**

# IDENTITY-SERVICE - CRUD LEGACY
spring.cloud.gateway.server.webmvc.routes[1].id=servicio2
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://Identity-Service
spring.cloud.gateway.server.webmvc.routes[1].predicates=Path=/api/user/**

# RESERVA-SERVICE
spring.cloud.gateway.server.webmvc.routes[2].id=servicio3
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://Reserva-Service
spring.cloud.gateway.server.webmvc.routes[2].predicates=Path=/api/reserva/**

# SERVICIO-SERVICE
spring.cloud.gateway.server.webmvc.routes[3].id=servicio4
spring.cloud.gateway.server.webmvc.routes[3].uri=lb://Reserva-Service
spring.cloud.gateway.server.webmvc.routes[3].predicates=Path=/api/servicio/**

# TIPOVEHICULO-SERVICE
spring.cloud.gateway.server.webmvc.routes[4].id=servicio5
spring.cloud.gateway.server.webmvc.routes[4].uri=lb://Vehiculo-Service
spring.cloud.gateway.server.webmvc.routes[4].predicates=Path=/api/tipoVehiculo/**

# VEHICULO-SERVICE
spring.cloud.gateway.server.webmvc.routes[5].id=servicio6
spring.cloud.gateway.server.webmvc.routes[5].uri=lb://Vehiculo-Service
spring.cloud.gateway.server.webmvc.routes[5].predicates=Path=/api/vehiculo/**

# PRODUCTO-SERVICE
spring.cloud.gateway.server.webmvc.routes[6].id=servicio7
spring.cloud.gateway.server.webmvc.routes[6].uri=lb://Producto-Service
spring.cloud.gateway.server.webmvc.routes[6].predicates=Path=/api/producto/**

# BOLETA-SERVICE
spring.cloud.gateway.server.webmvc.routes[7].id=servicio8
spring.cloud.gateway.server.webmvc.routes[7].uri=lb://Boleta-Service
spring.cloud.gateway.server.webmvc.routes[7].predicates=Path=/api/boleta/**

# AUTH - JWT
spring.cloud.gateway.server.webmvc.routes[8].id=auth-service
spring.cloud.gateway.server.webmvc.routes[8].uri=lb://Identity-Service
spring.cloud.gateway.server.webmvc.routes[8].predicates=Path=/auth/**

# Debe coincidir con Identity-Service
jwt.secret=HLa7EaO2i3rllQAkwUHGKdZtOO/ltRJ+BlGx44w0VtA=
